import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Link,
  Laptop,
  Loader2,
  Vote,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Monitor,
  CalendarCheck2,
  ShieldCheck,
} from '../../node_modules/lucide-react';
export const Icons = {
  logo: Command,
  close: X,
  file: FileText,
  link: Link,
  vote: Vote,
  screen: Monitor,
  secure: ShieldCheck,
  realtime: CalendarCheck2,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  product: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,

  twitter: Twitter,
  check: Check,
};
